export PATH="/usr/local/bin:$PATH"
export EDITOR="nvim"
export PATH=$HOME/go/bin:$PATH
export XDG_CURRENT_DESKTOP=Hyprland
export PATH=$PATH:/home/rootrim/.spicetify
export PATH="$PATH:/home/rootrim/.local/bin"
export PATH="$HOME/scripts:$PATH"
export QT_QPA_PLATFORMTHEME=qt6ct
export OPENAI_API_KEY=$(cat ~/.my_openai_api_key)
. "$HOME/.cargo/env"
