# Some variables
EDITOR=nvim

# Aliasses

alias ls="ls --color"
alias lah="ls -lah"
alias grep="grep --color=auto"
alias tree="tree -C"
alias zource="source ~/.zshrc"
alias la="ls -a"
alias dotf="cd ~/.dotfiles"
alias p="cd pyt"

# Plugins

source ~/.dotfiles/zsh/plugin_files/ohmyzsh-plugins/sudo-plugin.zsh
source ~/.dotfiles/zsh/plugin_files/ohmyzsh-plugins/command-not-found-plugin.zsh
source ~/.dotfiles/zsh/plugin_files/zsh-completions/zsh-completions.plugin.zsh
source ~/.dotfiles/zsh/plugin_files/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.dotfiles/zsh/plugin_files/fzf-tab/fzf-tab.plugin.zsh
source /usr/share/zsh/plugins/zsh-you-should-use/you-should-use.plugin.zsh
source ~/.dotfiles/zsh/plugin_files/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.dotfiles/zsh/plugin_files/zsh-history-substring-search/zsh-history-substring-search.zsh

# Binds

bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
bindkey '^[l' clear-screen

# zsh-completions Settings

autoload -U compinit && compinit
fpath=(~/.dotfiles/zsh/plugin-files/zsh-completions/src $fpath)

# Themes

# eval "$(starship init zsh)"
eval "$(oh-my-posh init zsh --config ~/.dotfiles/zsh/themes/oh-my-posh/zen.toml)"

# Set up fzf key bindings and fuzzy completion

eval "$(fzf --zsh)"

# Zoxide

eval "$(zoxide init --cmd cd zsh)"

# History

HISTSIZE=10000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion Styling

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'
